input {
  file {
    path => "/usr/share/logstash/logs/aiops.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  mutate {
    add_field => {
      "service" => "aiops-monitoring"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "aiops-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
